-- =============================================================================
-- PLANNED SESSIONS TABLE
-- Stores daily plans generated by OpenAI Coach Agent
-- =============================================================================

CREATE TABLE planned_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Date of the planned session
  date date NOT NULL,
  
  -- Status: planned, started, done, skipped
  status text NOT NULL DEFAULT 'planned'
    CHECK (status IN ('planned', 'started', 'done', 'skipped')),
  
  -- Context hash to detect when to regenerate
  context_hash text NOT NULL,
  
  -- Full plan JSON (verdict, summary, clipboard_text, plan.blocks, stop_rules)
  plan_json jsonb NOT NULL,
  
  -- Coach verdict (one of the keys in plan_json)
  verdict text NULL,
  
  -- When this plan was generated
  generated_at timestamptz NOT NULL DEFAULT now(),
  
  -- When the workout was completed (for done status)
  completed_at timestamptz NULL,
  
  -- Reason if skipped
  skip_reason text NULL,
  
  -- Audit
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  
  -- Unique constraint: one planned session per user per date
  UNIQUE(user_id, date)
);

-- Indexes
CREATE INDEX idx_planned_sessions_user_date 
  ON planned_sessions(user_id, date DESC);
CREATE INDEX idx_planned_sessions_user_status 
  ON planned_sessions(user_id, status);

-- RLS
ALTER TABLE planned_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY planned_sessions_select ON planned_sessions
  FOR SELECT USING (user_id = auth.uid());
CREATE POLICY planned_sessions_insert ON planned_sessions
  FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY planned_sessions_update ON planned_sessions
  FOR UPDATE USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY planned_sessions_delete ON planned_sessions
  FOR DELETE USING (user_id = auth.uid());
